@host = https://localhost:7233
@agentToken = PASTE_AGENT_TOKEN
@clientToken = PASTE_CLIENT_TOKEN

### A1. Login agenta
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{ "username": "agent1", "password": "Agent123!" }

### A2. Pogrešna lozinka
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{ "username": "agent1", "password": "pogresna" }

### A3. M2M token za eksterni CRM
POST {{host}}/api/v1/auth/token
Content-Type: application/json

{ "clientId": "crm-system", "clientSecret": "crm-secret-2026" }

### B1. Bez tokena
GET {{host}}/api/v1/rewards/my

### B2. Sa tokenom agenta
GET {{host}}/api/v1/rewards/my
Authorization: Bearer {{agentToken}}

### B3. Unos kupca
POST {{host}}/api/v1/rewards
Content-Type: application/json
Authorization: Bearer {{agentToken}}

{ "customerExternalId": 25, "note": "Loyal customer" }

### B4. Eksterni sistem pokušava unos
POST {{host}}/api/v1/rewards
Content-Type: application/json
Authorization: Bearer {{clientToken}}

{ "customerExternalId": 26 }

### B5. Eksterni sistem čita listu
GET {{host}}/api/v1/rewards?page=1&pageSize=20
Authorization: Bearer {{clientToken}}

### B6. Agent pokušava listu za admina/integraciju
GET {{host}}/api/v1/rewards
Authorization: Bearer {{agentToken}}

### B7. CRM lookup sa tokenom
GET {{host}}/api/v1/customers/25
Authorization: Bearer {{agentToken}}